### ISSUE TITLE
Maintain time duration on switch quality

### ISSUE THREAD

**Issue by CodeDruid13** [zikwall/re-player#2]
When switching between qualities, the video starts all over again. Can you update the player to be able to maintain duration when changing quality? And please show loading also if possible

**Comment by zikwall** [comment]
@CodeDruid13 Good idea, I'll do it in my spare time. But if you have such an opportunity, do not hesitate to make pull requests

**Comment by zikwall** [comment]
> And please show loading also if possible

I will think about how to implement this, I really like the flutter approach through the implementation of the [future Builder](https://api.flutter.dev/flutter/widgets/FutureBuilder-class.html):

```dart
@override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: controller.initializeVideoPlayerFuture,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.done) {
          return ValueListenableBuilder<bool>(
              valueListenable: controller.isFullScreen,
              builder: (_, bool isFullScreen, __) {
                return ReplayerOnFlutter(context, isFullScreen);
              });
        }

        return ReplayerOnFlutterPlayerContainerView(ProgressIndicator());
      },
    );
  }
```

**Comment by CodeDruid13** [comment]
For loading, adding activityindicator on play button, as long as duration is null or empty it will show

**Comment by zikwall** [comment]
@CodeDruid13 Now you can set your own component to display the content load status, example:

```js
<RePlayer
       progressComponent={
            <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
                    <Text style={{ color: '#fff' }}>Loading...</Text>
            </View>
       }
/>
```
